### ISSUE TITLE
img not being tagged in release

### ISSUE THREAD

**Issue by chazguerrero** [cadriel/FluiddPI#1]
Trying to follow the docs to install fluidpi suggests that the img is in the release archive. 

I was able to grab the img from the actions artifact so I'm good! But thought it would be good to bring this to your attention. 

If you need me to create a PR to do it let me know!

**Comment by cadriel** [comment]
FluiddPI is in the middle of a change, a new build is running now at which point new artifacts should be ready. Sorry for the inconvenience - all should be good in 30 or so minutes.

**Comment by cadriel** [comment]
Release is done, you should be good.
