### ISSUE TITLE
Image files?

### ISSUE THREAD

**Issue by micklug** [cadriel/FluiddPI#2]
where are the image files? Searched in all versions and didn't find it?

**Comment by cadriel** [comment]
FluiddPI is in the middle of a change, a new build is running now at which point new artifacts should be ready. Sorry for the inconvenience - all should be good in 30 or so minutes.

You'll be able to find the latest release here when that is complete;
https://github.com/cadriel/FluiddPI/releases

**Comment by cadriel** [comment]
Release is done, you should be good.
