### ISSUE TITLE
Wifi Reconnect

### ISSUE THREAD

**Issue by Bommel24** [cadriel/FluiddPI#3]
PI won't automatically reconnect to wifi until you do these steps:
https://raspberrypi.stackexchange.com/a/5341
This should be default in firmware (in my opinion) since losing the connection removes the ability to force stop the printer.

**Comment by cadriel** [comment]
This already happens as a part of CustomPiOS's network module.

https://github.com/guysoft/CustomPiOS/blob/devel/src/modules/network/start_chroot_script#L44
