### ISSUE TITLE
Using Docker and FluiddPi

### ISSUE THREAD

**Issue by treehuggersystems** [cadriel/FluiddPI#4]
Hello, I started by using a fresh install of Raspian Lite OS as my base install for my Pi4. Then I installed docker as per many "how to's" on the internet for Raspberry Pi. Once I had docker installed I followed the directions here https://hub.docker.com/r/cadriel/fluidd
and got fluidd to work. But when logging into the web browser I found in an error state: No moonraker connection. Please check moonraker status and / or refresh. 

I tried to find a solid fix by googling, like all good programmers, but I found nothing. Is it perhaps something in my architecture that was causing it to foul?

**Comment by cadriel** [comment]
The container only hosts Fluidd, not the other components for a working printer / firmware.

I.e., you should have Klipper and Moonraker setup and configured elsewhere on your network - and then have Fluidd connect to the appropriate moonraker endpoint.

Keep in mind that Moonraker would need the correct cors configuration for the given fluidd instance to correctly connect.
