### ISSUE TITLE
More instructions on how to set up camera?

### ISSUE THREAD

**Issue by leandrotoledo** [cadriel/FluiddPI#8]
Hi!

I'm using FLuiddPi and trying to set up a camera. I came across this article:
https://docs.fluidd.xyz/features/cameras

But I can't find `/boot/webcam.txt`, or even `/boot/fluiddpi.txt`. Maybe I'm missing something?

Camera type: Logitech C270
Enabled under Settings with Stream typ: MJPEG Adaptive
Camera URL: /webcam/?action=stream

Thanks a lot for this image!

**Comment by leandrotoledo** [comment]
I figured out, the webcam.txt is in fact accessible via Fluidd's webinterface. From there I simply uncommented `camera="auto"` and after restarting the host it started working.

**Comment by killer1kay** [comment]
> > To get started, open the webcam.txt config file in Fluidd’s configuration editor. Instructions on how to get started as well as option references are included in this file.
> 
> I might be missing something fundamental here but webcam.txt was not generated in my fresh install of Fluidd ![image](https://user-images.githubusercontent.com/71470021/239490276-99a1bd05-15c4-46d3-8fbc-c2c1c3e25f81.png)

same I don't see that file
